### ISSUE TITLE
Update Google Analytics

### ISSUE THREAD

**Issue by glitchedmob** [sgfdevs/sgf-covid-support#1]
@jason-klein  do we have a SGF Devs or Hack4Good Google account where we can generate a new google analytics project?

**Comment by jason-klein** [comment]
@glitchedmob  I added the following "H4G Covid Support Web" property to the existing "Hack 4 Good" account under Devs.

Tracking ID
UA-153190642-2

GA shows your gmail as an admin for "Hack 4 Good". PM me if you need to add another email.
